//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace buoi08.Areas.Admin.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienHe
    {
        public int MaLienHe { get; set; }
        public string Ten { get; set; }
        public string Gmail { get; set; }
        public string TinNhan { get; set; }
        public Nullable<int> MaKH { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
